benchmarks:
    - irq-lat:
        - baremetal_benchmark:
            - bin_name: "guest_1"
            - flags: 
                - rh850-u2a16: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"
                - tc4dx: "FLASH_BASE=0xA000000 FLASH_SIZE=0x8000 RAM_BASE=0x9000000 RAM_SIZE=0x1000"
                - s32: ""
                - qemu-aarch64-virt: ""

    - ctx_switch:
        - baremetal_benchmark:
            - bin_name: "guest_1"
            - flags: 
                - rh850-u2a16: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"
                - tc4dx: "FLASH_BASE=0xA000000 FLASH_SIZE=0x8000 RAM_BASE=0x9000000 RAM_SIZE=0x1000"
                - s32: ""
                - qemu-aarch64-virt: ""
        - baremetal_benchmark:
            - bin_name: "guest_2"
            - flags: 
                - rh850-u2a16: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"
                - tc4dx: "FLASH_BASE=0xA000000 FLASH_SIZE=0x8000 RAM_BASE=0x9000000 RAM_SIZE=0x1000"
                - s32: ""
                - qemu-aarch64-virt: ""