tests:
    boot:
        - list_tests: ""
        - list_suites: "BOOT_CHECK"

    irq:
        - list_tests: ""
        - list_suites: "IRQ_CHECK"

    performance:
        - list_tests: "IRQ_LATENCY"
        - list_suites: "IRQ_CHECK"

setups:
    baremetal:
        - baremetal:
            - bin_name: "baremetal"
            - flags: " "

    benchmark:
        - baremetal_benchmark:
            - bin_name: baremetal_sender
            - flags: ""
