tests:
    boot:
        - list_tests: ""
        - list_suites: "BOOT_CHECK"

    irq:
        - list_tests: ""
        - list_suites: "IRQ_CHECK"

    performance:
        - list_tests: "IRQ_LATENCY"
        - list_suites: "IRQ_CHECK"

setups:
    tests:
        baremetal:
            - baremetal:
                - bin_name: "baremetal"
                - flags: " "

    benchmark:
        - baremetal_benchmark:
            - bin_name: baremetal_sender
            - flags: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"
        - baremetal_benchmark:
            - bin_name: baremetal_receiver
            - flags: "FLASH_BASE=0x00000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"

        - irq-lat:
            - baremetal_guest_1:
                - bin_name: guest_1
                - flags: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"

        - ctx_switch:
            - baremetal_guest_1:
                - bin_name: guest_1
                - flags: "FLASH_BASE=0x10000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"
            - baremetal_guest_2:
                - bin_name: guest_2
                - flags: "FLASH_BASE=0x00000 FLASH_SIZE=0x6000 RAM_BASE=0xfe100000 RAM_SIZE=0x8000"

