#  Copyright (c) Bao Project and Contributors. All rights reserved
#  SPDX-License-Identifier: Apache-2.0

# Hook for bao-baremetal-test, whose src/tests/setup.mk includes
# $(TESTF_TESTS_DIR)/src/bao-test.mk and appends TESTF_SRCS, TESTF_INC_DIR and
# TESTF_FLAGS to its build. kao points TESTF_TESTS_DIR at this guest folder;
# the harness and headers are compiled from kao's shared src/kao, and the
# generated files from KAO_GEN_DIR. Nothing is copied.

ifndef TESTF_TESTS_DIR
$(error TESTF_TESTS_DIR must point at kao's src/kao/guests/baremetal directory)
endif
ifndef KAO_GEN_DIR
$(error KAO_GEN_DIR must point at the directory holding kao's generated sources)
endif

KAO_DIR:=$(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../../..)
TESTF_SRC_DIR:=$(KAO_DIR)
TESTF_INC_DIR:=$(KAO_DIR)/inc $(KAO_DIR)/guests/baremetal/inc

# kao_tests.c is generated by kao: it includes the selected test sources and
# defines the table the harness walks.
TESTF_SRCS += $(KAO_DIR)/kao.c $(KAO_GEN_DIR)/kao_tests.c

ifdef KAO_LOG_LEVEL
TESTF_FLAGS+=-DKAO_LOG_LEVEL=$(KAO_LOG_LEVEL)
endif

ifdef KAO_NO_RTE
TESTF_FLAGS+=-Dno_rte
endif

# Preprocess kao_all.c (generated by kao, includes every candidate source) and
# print the KAO_TEST marker lines, using the same compiler and flags as the build.
# This file is included before the guest's build rules, so the default goal is
# put back to whatever it was.
kao_default_goal:=$(.DEFAULT_GOAL)
.PHONY: kao-discover
kao-discover:
	@$(cc) $(filter-out -MD -MF $@.d,$(CFLAGS)) -DKAO_DISCOVERY -E -P \
		$(KAO_GEN_DIR)/kao_all.c | grep '@KAO_' || true
.DEFAULT_GOAL:=$(kao_default_goal)
