# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Bao Project and Contributors. All rights reserved


"""
Test discovery and code generation for the kao harness.

Discovery is done by the C preprocessor: kao writes testf_all.c including every
candidate source, the guest build preprocesses it with TESTF_DISCOVERY defined,
and each BAO_TEST registration comes back as one marker line that is read here.
The build then compiles a single generated testf_tests.c that includes the
sources holding selected tests and ends with the table of selected descriptors.
"""


import os
import re


_STRING = r'(?:"(?:\\.|[^"\\])*"\s*)+'
_MARKER_RE = re.compile(
    r"@BAO_TEST@\s+(\S+)\s+@\s+(\S+)\s+@\s+(" + _STRING + r")@\s+(" + _STRING
    + r")@\s+(" + _STRING + r")@\s+(" + _STRING + r")@\s+(\d+)\s+@"
)
_STRING_LITERAL_RE = re.compile(r'"((?:\\.|[^"\\])*)"')
_ID_TOKEN_RE = re.compile(r"^[A-Za-z0-9_]+$")
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]+$")

ALL_SOURCE = "testf_all.c"
TESTS_SOURCE = "testf_tests.c"

_GENERATED_BANNER = (
    "/*\n"
    " * Copyright (c) Bao Project and Contributors. All rights reserved\n"
    " *\n"
    " * SPDX-License-Identifier: Apache-2.0\n"
    " *\n"
    " * Generated by bao-kao. Do not edit.\n"
    " */\n"
)


def unquote(literals):
    """Join adjacent C string literals into one Python string."""
    pieces = [match.group(1) for match in _STRING_LITERAL_RE.finditer(literals)]
    return "".join(pieces).encode("utf-8").decode("unicode_escape")


def _token_list(literals, kind):
    tokens = []
    for token in unquote(literals).split(","):
        token = token.strip().lower()
        if not token:
            continue
        if not _TOKEN_RE.match(token):
            raise ValueError(f"invalid {kind} token '{token}'")
        if token not in tokens:
            tokens.append(token)
    return tokens


def list_sources(src_root, sources=None):
    """C files to hand to discovery: all of src_root, or the given entries.

    Directories listed in sources are scanned non-recursively, so a project can
    hand kao exactly the subtrees that apply to a build. Paths are reported
    relative to src_root, so every entry must lie under it.
    """
    src_root = os.path.abspath(src_root)
    if not sources:
        files = []
        for root, dirs, names in os.walk(src_root):
            dirs.sort()
            files.extend(os.path.join(root, n) for n in sorted(names) if n.endswith(".c"))
        return [os.path.relpath(f, src_root) for f in files]

    files = []
    for entry in sources:
        entry = os.path.abspath(entry)
        if os.path.commonpath([src_root, entry]) != src_root:
            raise ValueError(f"test source '{entry}' is not under '{src_root}'")
        if os.path.isdir(entry):
            files.extend(
                os.path.join(entry, n) for n in sorted(os.listdir(entry)) if n.endswith(".c")
            )
        elif os.path.isfile(entry):
            files.append(entry)
        else:
            raise ValueError(f"test source '{entry}' does not exist")
    return [os.path.relpath(f, src_root) for f in dict.fromkeys(files)]


def _parse_marker(match, src_root):
    test_id, name, tags, envs, desc, file_literal, line = match.groups()
    rel_path = os.path.relpath(os.path.abspath(unquote(file_literal)), src_root)
    where = f"{rel_path}:{line}"

    if not _ID_TOKEN_RE.match(test_id):
        raise ValueError(f"{where}: test id must be letters, digits and '_', got '{test_id}'")
    if not _IDENTIFIER_RE.match(name):
        raise ValueError(f"{where}: '{name}' is not a valid function identifier")
    try:
        tag_list = _token_list(tags, "tag")
        env_list = _token_list(envs, "environment")
    except ValueError as exc:
        raise ValueError(f"{where}: {exc}") from exc
    if not env_list:
        raise ValueError(f"{where}: test {test_id} declares no environment")

    return {
        "id": test_id,
        "name": name,
        "tags": tag_list,
        "envs": env_list,
        "description": unquote(desc),
        "file": rel_path,
        "line": int(line),
    }


def parse_discovery(output, src_root):
    """Turn the marker lines printed by `make testf-discover` into test records."""
    src_root = os.path.abspath(src_root)
    tests = [_parse_marker(match, src_root) for match in _MARKER_RE.finditer(output)]

    by_id = {}
    for test in tests:
        by_id.setdefault(test["id"], []).append(test)
    duplicates = {i: entries for i, entries in by_id.items() if len(entries) > 1}
    if duplicates:
        details = "; ".join(
            f"id {test_id} in "
            + ", ".join(f"{t['file']}:{t['line']} ({t['name']})" for t in entries)
            for test_id, entries in sorted(duplicates.items())
        )
        raise ValueError(f"duplicate test ids: {details}")
    return tests


def render_all_source(files, src_root):
    """Render testf_all.c, the discovery unit including every candidate source."""
    lines = [_GENERATED_BANNER, '#include "testf.h"', ""]
    lines.extend(f'#include "{os.path.join(src_root, path)}"' for path in files)
    lines.append("")
    return "\n".join(lines)


def render_tests_source(tests, src_root):
    """Render testf_tests.c: the selected sources and the table, in that order."""
    ordered = list({test["id"]: test for test in tests}.values())
    files = list(dict.fromkeys(test["file"] for test in ordered))

    lines = [_GENERATED_BANNER, '#include "testf.h"', ""]
    lines.extend(f'#include "{os.path.join(src_root, path)}"' for path in files)
    lines.append("")
    lines.append("const struct testf_test* const testf_tests[] = {")
    lines.extend(f"    &testf_test_{test['id']}," for test in ordered)
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int testf_tests_num = {len(ordered)};")
    lines.append("")
    return "\n".join(lines)


def write_all_source(files, src_root, gen_dir):
    """Write testf_all.c for discovery into gen_dir and return its path."""
    os.makedirs(gen_dir, exist_ok=True)
    path = os.path.join(gen_dir, ALL_SOURCE)
    with open(path, "w", encoding="utf8") as out:
        out.write(render_all_source(files, os.path.abspath(src_root)))
    return path


def write_tests_source(tests, src_root, gen_dir):
    """Write testf_tests.c for the given selection into gen_dir and return its path."""
    os.makedirs(gen_dir, exist_ok=True)
    path = os.path.join(gen_dir, TESTS_SOURCE)
    with open(path, "w", encoding="utf8") as out:
        out.write(render_tests_source(tests, os.path.abspath(src_root)))
    return path
