#  Copyright (c) Bao Project and Contributors. All rights reserved
#  SPDX-License-Identifier: Apache-2.0

# Hook for bao-baremetal-test, whose src/tests/setup.mk includes
# $(TESTF_TESTS_DIR)/src/bao-test.mk and appends TESTF_SRCS, TESTF_INC_DIR and
# TESTF_FLAGS to its build. kao points TESTF_TESTS_DIR at this guest folder;
# the harness and headers are compiled from kao's shared src/kao, and the
# generated files from TESTF_GEN_DIR. Nothing is copied.

ifndef TESTF_TESTS_DIR
$(error TESTF_TESTS_DIR must point at kao's src/testf/guests/baremetal directory)
endif
ifndef TESTF_GEN_DIR
$(error TESTF_GEN_DIR must point at the directory holding kao's generated sources)
endif

TESTF_DIR:=$(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../../..)
TESTF_SRC_DIR:=$(TESTF_DIR)
TESTF_INC_DIR:=$(TESTF_DIR)/inc $(TESTF_DIR)/guests/baremetal/inc

# testf_tests.c is generated by kao: it includes the selected test sources and
# defines the table the harness walks.
TESTF_SRCS += $(TESTF_DIR)/testf.c $(TESTF_GEN_DIR)/testf_tests.c

ifdef TESTF_LOG_LEVEL
TESTF_FLAGS+=-DTESTF_LOG_LEVEL=$(TESTF_LOG_LEVEL)
endif

ifdef TESTF_NO_RTE
TESTF_FLAGS+=-Dno_rte
endif

# Preprocess testf_all.c (generated by kao, includes every candidate source) and
# print the BAO_TEST marker lines, using the same compiler and flags as the build.
# This file is included before the guest's build rules, so the default goal is
# put back to whatever it was.
testf_default_goal:=$(.DEFAULT_GOAL)
.PHONY: testf-discover
testf-discover:
	@$(cc) $(filter-out -MD -MF $@.d,$(CFLAGS)) -DTESTF_DISCOVERY -E -P \
		$(TESTF_GEN_DIR)/testf_all.c | grep '@BAO_' || true
.DEFAULT_GOAL:=$(testf_default_goal)
